Mango.Web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace Mango.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        private readonly ITokenProvider _tokenProvider;

        public AuthController(IAuthService authService, ITokenProvider tokenProvider)
        {
            _authService = authService;
            _tokenProvider = tokenProvider;
        }
        [HttpGet]
        public IActionResult Login()
        {
            LoginDTO model = new();
            return View(model);
        }
        [HttpGet]
        public IActionResult Register()
        {
            var roleList = new List<SelectListItem>() {
                new SelectListItem{ Text = SD.RoleAdmin, Value = SD.RoleAdmin},
                new SelectListItem{ Text = SD.RoleCustomer, Value = SD.RoleCustomer}
            };
            ViewBag.RoleList = roleList;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegistrationDTO request)
        {
            ResponseDTO response = await _authService.RegisterAsync(request);
            ResponseDTO? assignRole = new();
            if (response is not null && response.IsSuccess)
            {
                request.Role = string.IsNullOrEmpty(request.Role) ? SD.RoleCustomer : request.Role;
                assignRole = await _authService.AssignRoleAsync(request);
            }
            if (assignRole is not null && assignRole.IsSuccess)
            {
                TempData["success"] = "Registration Successful";
                return RedirectToAction("Login");
            }
            var roleList = new List<SelectListItem>() {
                new SelectListItem{ Text = SD.RoleAdmin, Value = SD.RoleAdmin},
                new SelectListItem{ Text = SD.RoleCustomer, Value = SD.RoleCustomer}
            };
            TempData["error"] = response.Message;
            ViewBag.RoleList = roleList;
            return View(request);
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            _tokenProvider.ClearToken();
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginDTO request)
        {
            ResponseDTO response = await _authService.LoginAsync(request);
            if (response is not null && response.IsSuccess)
            {
                LoginResponseDTO loginResp = JsonConvert.DeserializeObject<LoginResponseDTO>(
                    Convert.ToString(response.Result));
                _tokenProvider.SetToken(loginResp.Token);
                await SignInUser(loginResp);
                TempData["success"] = "Logged in Successfully";
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("CustomError", response.Message);
            return View(request);
        }
        private async Task SignInUser(LoginResponseDTO model)
        {
            var handler = new JwtSecurityTokenHandler();
            var jwt = handler.ReadJwtToken(model.Token);
            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email, jwt.Claims.FirstOrDefault(
                x => x.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub, jwt.Claims.FirstOrDefault(
                x => x.Type == JwtRegisteredClaimNames.Sub).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name, jwt.Claims.FirstOrDefault(
                x => x.Type == JwtRegisteredClaimNames.Name).Value));
            identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(
                x => x.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(
                x => x.Type == "role").Value));

            var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
        }
    }
}

Mango.Web/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Connections.Features;
using Microsoft.AspNetCore.Mvc;
using System.IdentityModel.Tokens.Jwt;

namespace Mango.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly ICouponService _couponService;

        public CartController(ICartService cartService, ICouponService couponService)
        {
            _cartService = cartService;
            _couponService = couponService;
        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await LoadCartDTO());
        }
        public async Task<IActionResult> Remove(int cartDetailsId)
        {
            ResponseDTO? response = await _cartService.RemoveCartAsync(cartDetailsId);
            if (response is not null && response.IsSuccess)
            {
                TempData["success"] = "Item has been successfully removed";
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ApplyCoupon(CartDTO cart)
        {
            cart.CartDetails = new List<CartDetailsDTO>();
            var response = await _cartService.ApplyCouponAsync(cart);
            if (response is not null && response.IsSuccess)
            {
                TempData["success"] = "Coupon applied successfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Unable to apply coupon";
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> RemoveCoupon(CartDTO cart)
        {
            cart.CartDetails = new List<CartDetailsDTO>();
            cart.CartHeader.CouponCode = "";
            var response = await _cartService.ApplyCouponAsync(cart);
            if (response is not null && response.IsSuccess)
            {
                TempData["success"] = "Coupon applied successfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Unable to apply coupon";
            return RedirectToAction("Index");
        }
        private async Task<CartDTO> LoadCartDTO()
        {
            var userId = User.Claims?.Where(x => x.Type == JwtRegisteredClaimNames.Sub).FirstOrDefault().Value;
            var response = await _cartService.GetCartByUserIdAsync(userId);
            if (response is not null && response.IsSuccess)
            {
                CartDTO? cart = JsonConvert.DeserializeObject<CartDTO>(
                    Convert.ToString(response.Result));
                return cart;
            }
            return new();
        }

    }
}

Mango.Web/Controllers/CouponController.cs
using Mango.Web.Models;
using Mango.Web.Service.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Mango.Web.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;

        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }

        public async Task<IActionResult> Index()
        {
            List<CouponDTO> objList = new();
            ResponseDTO response = await _couponService.GetAllCouponsAsync();
            if (response is not null && response.IsSuccess)
            {
                objList = JsonConvert.DeserializeObject<List<CouponDTO>>(Convert.ToString(response.Result));
            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return View(objList);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CouponDTO coupon)
        {
            if (ModelState.IsValid)
            {
                ResponseDTO response = await _couponService.CreateCouponAsync(coupon);
                if (response is not null && response.IsSuccess)
                {
                    TempData["success"] = "Coupon successfully created";
                    return RedirectToAction("Index");
                }
                TempData["error"] = response?.Message;
            }
            return View(coupon);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _couponService.GetCouponByIdAsync(id);
            if (response is not null && response.IsSuccess)
            {
                var coupon = JsonConvert.DeserializeObject<CouponDTO>(Convert.ToString(response.Result));
                return View(coupon);
            }
            TempData["error"] = response.Message;
            return NotFound();
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePOST(int id)
        {
            var response = await _couponService.DeleteCouponAsync(id);
            if (response is not null && response.IsSuccess)
            {
                TempData["success"] = "Coupon successfully deleted";
                return RedirectToAction("Index");
            }
            TempData["error"] = response.Message;
            return NotFound();
        }
    }
}

Mango.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace Mango.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> Index()
        {
            List<ProductDTO> objList = new();
            ResponseDTO response = await _productService.GetAllProductsAsync();
            if (response is not null && response.IsSuccess)
            {
                objList = JsonConvert.DeserializeObject<List<ProductDTO>>(
                    Convert.ToString(response.Result));
            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return View(objList);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ProductDTO model)
        {
            if (ModelState.IsValid)
            {
                ResponseDTO response = await _productService.CreateProductAsync(model);
                if (response is not null && response.IsSuccess)
                {
                    TempData["success"] = "Product successfully craeted";
                    return RedirectToAction("Index");
                }
                TempData["error"] = response?.Message;
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _productService.GetProductByIdAsync(id);
            if (response is not null && response.IsSuccess)
            {
                var product = JsonConvert.DeserializeObject<ProductDTO>(Convert.ToString(response.Result));
                return View(product);
            }
            TempData["error"] = response.Message;
            return NotFound();
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePOST(int id)
        {
            var response = await _productService.DeleteProductAsync(id);
            if (response is not null && response.IsSuccess)
            {
                TempData["success"] = "Product successfully deleted";
                return RedirectToAction("Index");
            }
            TempData["error"] = response?.Message;
            return NotFound();
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var response = await _productService.GetProductByIdAsync(id);
            if (response is not null && response.IsSuccess)
            {
                var product = JsonConvert.DeserializeObject<ProductDTO>(Convert.ToString(response.Result));
                return View(product);
            }
            TempData["error"] = response?.Message;
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Update(ProductDTO product)
        {
            var response = await _productService.UpdateProductAsync(product);
            if (response is not null && response.IsSuccess)
            {
                TempData["success"] = "Product updated successfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = response?.Message;
            return View(product);
        }
    }
}

Mango.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mango.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mango.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mango.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Coupon" asp-action="Index">Coupon</a></li>
                                <li><a class="dropdown-item" asp-controller="Product" asp-action="Index">Product</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="Index"><i class="bi bi-cart"></i></a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="#">Hello, @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications" />
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="text-center">
            Made with ♡ by Purits
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Mango.Web/Views/Shared/_Notifications.cshtml
@if (TempData["success"] is not null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] is not null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        toastr.error('@TempData["Error"]');
    </script>
}